adbelt/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls", namespace="main")),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from  .import views
from main.views import*


app_name = "main"


urlpatterns = [
    path('', views.index, name="index"),
    path('about-us/', views.aboutus, name='aboutus'),
    path('training/', views.training, name='training'),
    path('supplies/', views.eqpt, name='eqpt')
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render

# Create your views here.
# Create your views here.
def index(request):
    return render(request, "main/index.html", {})


def training(request):
    return render(request, "main/serv.html", {})

def eqpt(request):
    return render(request, "main/eqpt.html", {})


def aboutus(request):
    return render(request, "main/aboutus.html", {})

main/templates/base/navbar.html
{% load static %}

<section>
    <div class="container">
        <div class="row">
            <div>
                <nav class="navbar navbar-expand-lg">
                    <!--Logo-->
                    <div class="logo"></div>
                    <ul class="nav-links">
                        <input type="checkbox" id="checkbox_toggle" />
                        <label for="checkbox_toggle" class="hamburger">&#9776;</label>

                <!-- NAVIGATION MENUS -->
                        <div class="menu">
                            <li><a href="/">Home</a></li>
                            <li><a href="/">About</a></li>
                            <li><a href="/">Referrals</a></li>
                        </div>
                    </ul>
                </nav>
                    
            </div>
        </div>
    </div>
</section>

main/templates/main/aboutus.html
{% extends "main/base.html" %}
{% load static %}


{% block content %}
    <section id="top" class="text-center" style="overflow-x:hidden;height: 100%;">
            <!--title section-->
        {% include "main/snippets/topbar.html" %}



        <div class="sectors-about">
            <h4 class="sechead-about">ABOUT US</h4>
            <hr />
            <p>
                ADBELT CONSULTS LIMITED is your strategic HSE partner, offering professional support in Health, Safety, and Environment.
                Our highly trained team has wide experience across sectors like manufacturing, construction, public sector, mining, and oil and gas.
                We're ready to take on your challenges with our knowledge, skills, and passion. Let's write history together—give us the opportunity to be part of your
                story and overcome challenges with innovative solutions. Our services, including inspections, audits, supplies,
                and trainings, are tailored to drive HSE in your organization.
                We create safe, healthy, and sustainable working environments, optimize HSE performance, streamline processes, and ensure regulatory compliance.
            </p>
        </div>
        <h2 class="about-header">WHO WE ARE</h2>
        <div class="values-section">
            <div class="value">
                <h3>Our Vision</h3>
                <p>
                    To be the preferred HSE consultancy.
                </p>
            </div>
            <div class="value">
                <h3>Our Purpose</h3>
                <p>
                    To empower organisations to integrate health, safety, and environment best practices
                    in all the aspects of organisation’s processes, systems and work practices to ensure sustainability
                </p>
            </div>
            <div class="value">
                <h3>Core Values</h3>
                <ul>
                    <li>Professionalism </li>
                    <li>Integrity</li>
                    <li>Customer centricity</li>
                    <li>Teamwork</li>
                </ul>
            </div>
        </div>
        {% include "main/snippets/footer.html" %}
    </section>

{% endblock %}

main/templates/main/eqpt.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
    <section id="top" class="text-center" style="overflow-x:hidden;height: 100%;">
            <!--title section-->
        {% include "main/snippets/topbar.html" %}
        <div class="sectors-eq">
            <div class="sec-eqp">
                <h4 class="sechead">PERSONAL PROTECTIVE  EQUIPMENT</h4>
                <h5 class="sechead5">Reach out for any Safety Equipments!</h5>

                <div class="secmajor">
                    <div class="sec-eqp1">
                        <h5>Head Protection</h5>
                        <img src="../../static/main/images/head.jpg" alt="ppe" />
                    </div>
                    <div class="sec-eqp1">
                        <h5>Eye protection</h5>
                        <img src="../../static/main/images/eye.png" alt="ppe" />
                    </div>
                    <div class="sec-eqp1">
                        <h5>Ear protection</h5>
                        <img src="../../static/main/images/ear.jpg" alt="fire" />
                    </div>
                    <div class="sec-eqp1">
                        <h5>Respiratory Protection</h5>
                        <img src="../../static/main/images/lungs.png" alt="aid" />
                    </div>
                    <div class="sec-eqp1">
                        <h5>Hand protection</h5>
                        <img src="../../static/main/images/hand.png" alt="aid" />
                    </div>
                    <!-- <div class="sec-eqp1">-->
                    <!--    <h5>Body Protection</h5>-->
                    <!--    <img src="../../static/main/images/body.png" alt="ppe" />-->
                    <!--</div>-->
                    <!--<div class="sec-eqp1">-->
                    <!--    <h5>Feet protection</h5>-->
                    <!--    <img src="../../static/main/images/feet.jpg" alt="ppe" />-->
                    <!--</div>-->
                    <!--<div class="sec-eqp1">-->
                    <!--    <h5>Fall  protection</h5>-->
                    <!--    <img src="../../static/main/images/lifelines.jpg" alt="fire" />-->
                    <!--</div>-->
                    <!--<div class="sec-eqp1">-->
                    <!--    <h5>Respiratory Protection</h5>-->
                    <!--    <img src="../../static/main/images/lungs.png" alt="aid" />-->
                    <!--</div>-->
                    <!--<div class="sec-eqp1">-->
                    <!--    <h5>Hand protection</h5>-->
                    <!--    <img src="../../static/main/images/hand.png" alt="aid" />-->
                    <!--</div>-->
                </div>
                <!--<div class="secmajor">-->
                <!--    <div class="sec-eqp1">-->
                <!--        <h5>Body Protection</h5>-->
                <!--        <img src="../../static/main/images/body.png" alt="ppe" />-->
                <!--    </div>-->
                <!--    <div class="sec-eqp1">-->
                <!--        <h5>Feet protection</h5>-->
                <!--        <img src="../../static/main/images/feet.jpg" alt="ppe" />-->
                <!--    </div>-->
                <!--    <div class="sec-eqp1">-->
                <!--        <h5>Fall  protection</h5>-->
                <!--        <img src="../../static/main/images/lifelines.jpg" alt="fire" />-->
                <!--    </div>-->
                <!--    <div class="sec-eqp1">-->
                <!--        <h5>Respiratory Protection</h5>-->
                <!--        <img src="../../static/main/images/lungs.png" alt="aid" />-->
                <!--    </div>-->
                <!--    <div class="sec-eqp1">-->
                <!--        <h5>Hand protection</h5>-->
                <!--        <img src="../../static/main/images/hand.png" alt="aid" />-->
                <!--    </div>-->
                <!--</div>-->


            </div>
            <div class="sec-eqp">
                <h4 class="sechead">HSE EQUIPMENT</h4>

                <div class="secmajor">
                    <div class="sec-eqp1">
                        <h5>Energy Isolation Eqpt</h5>
                        <img src="../../static/main/images/lock.png" alt="ppe" />
                    </div>
                    <div class="sec-eqp1">
                        <h5>Safety Signage</h5>
                        <img src="../../static/main/images/sign.png" alt="ppe" />
                    </div>
                    <div class="sec-eqp1">
                        <h5>Fire safety Equipment</h5>
                        <img src="../../static/main/images/firesafe.jpg" alt="fire" />
                    </div>
                    <div class="sec-eqp1">
                        <h5>First Aid Equipment</h5>
                        <img src="../../static/main/images/aid.png" alt="aid" />
                    </div>

                </div>
            </div>
        </div>
        {% include "main/snippets/footer.html" %}
    </section>

{% endblock %}

main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
    <section id="top" class="text-center" style="overflow-x:hidden;height: 100%;overflow-y:auto;">
            <!--title section-->
        {% include "main/snippets/topbar.html" %}
        <!-- <h4 class="nhead">ADBELT CONSULTS (U) LTD</h4> -->
        <div class="nana-new">
            <div class="nana-text">
                <h1>ADBELT CONSULTS LIMITED</h1>
                <h4>
                   HSE Consultancy
                </h4>
                <!--<h6>-->
                <!--    We seek to empower organisations to integrate health, safety, and environment best practices-->
                <!--    in all the aspects of organisation’s processes, systems and work practices to ensure sustainability-->
                <!--</h6>-->
                <h6>
                    Driving Sustainability
                </h6>
                <a href="#contactus">
                    <button>
                        Inquire
                    </button>
                </a>

            </div>
        </div>
        <!-- <div class="addiv">
            <h4 class="ad">WELCOME,</h4>
            <p class="pad">
                Adbelt consults (U) Ltd  is a management,
                inspection, consultancy and training company founded and registered
                in Uganda. We are occupational health, safety, and environmental
                consultants that prepare, maintain, assess, and promote safety and
                health standards within the private, public companies and organizations
                in accordance with the current legislation both local and international.
            </p>
        </div> -->
        <div id="sectors" class="sectors">
            <h4 class="sechead">OUR SECTORS</h4>
            <div class="secdiv">
                <div class="sec">
                    <h5>ENERGY</h5>
                    <hr class="newhr">
                    <p>
                        We offer Consultancy services in energy sectors such as Refineries,
                        Power Generation plants and more..
                    </p>
                </div>
                <div class="sec">
                    <h5>MANUFACTURING</h5>
                    <hr class="newhr">
                    <p>
                        We offer Consultancy services in Manufacturing processes,such as
                        Sugar plants, Steel processes.Textiles and others
                    </p>
                </div>
                <div class="sec">
                    <h5>OIL AND GAS</h5>
                    <hr class="newhr">
                    <p>
                        Are you dealing in Refinery, Oil Drilling,Petroleum Products.
                        Reach out
                    </p>
                </div>
                <div class="sec">
                    <h5>PUBLIC SECTOR</h5>
                    <hr class="newhr">
                    <p>
                       We train staff of public companies about the latest Safety practices within the
                       Organization
                    </p>
                </div>
                <div class="sec">
                    <h5>CONSTRUCTION</h5>
                    <hr class="newhr">
                    <p>
                        We offer Top-notch safety practices for construction Workers and Engineers.
                    </p>
                </div>
                <div class="sec">
                    <h5>HEALTH CARE</h5>
                    <hr class="newhr">
                    <p>
                        We Equip Health Workers about the best safety measures For a better healthy
                        Environment.
                    </p>
                </div>
            </div>
        </div>
        {% include "main/snippets/footer.html" %}
    </section>

{% endblock %}

main/templates/main/serv.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
    <section id="top" class="text-center" style="overflow-x:hidden;height: 100%;">
            <!--title section-->
        {% include "main/snippets/topbar.html" %}
        <h4 class="serv">OUR SERVICES</h4>
        <!-- <h6 class="serv6"> === We offer a wide Range of Services ===</h6> -->
        <div id="inspect" class="train-main">
            <div class="train-sub">
                <h3>HSE INSPECTIONS</h3>
                <!-- <hr /> -->
                <p>
                    At Adbelt Consults Limited, we conduct workplace HSE inspections for their sites, machinery and equipment,
                    processes to identify hazards and risks and develop an action plan of the mitigation measures to address
                    the HSE hazards and risks including machinery hazards, psychological hazards, biological and chemical hazards,
                    ergonomic and physical hazards. This helps our clients to eliminate workplace injuries and cases
                    of ill-health. We follow the international standards in executing our work with unmatched professionalism.
                </p>
            </div>
            <div>
                <img src="../../static/main/images/hsetrain.jpg" />
            </div>
        </div>
        <div  id = "audit" class="train-main1">
            <div>

                <!-- <hr /> -->
                <img src="../../static/main/images/hseaudit.jpg" />

            </div>
            <div class="train-sub2">
                <h3>HSE AUDITS</h3>
                <p>
                    At Adbelt Consults Limited, we conduct workplace HSE inspections for their sites, machinery and equipment,
                    processes to identify hazards and risks and develop an action plan of the mitigation measures to address
                    the HSE hazards and risks including machinery hazards, psychological hazards, biological and chemical hazards,
                    ergonomic and physical hazards. This helps our clients to eliminate workplace injuries and cases
                    of ill-health. We follow the international standards in executing our work with unmatched professionalism.
                </p>
            </div>
        </div>
        <div  id="train" class="train-main3">
            <div class="train-sub3">
                <h3>TRAININGS</h3>
                <!-- <hr /> -->
                <p>
                    In our ambition empower to organisations to integrate the best HSE practices with in their
                    operations, we conduct well developed trainings that are tailored to be effective and elaborate
                    to the different sectors. These trainings aid in raising awareness in regards to health, safety and
                     environment. At Adbelt Consults limited, we have qualified and experienced HSE professionals that
                     conduct both practical and theoretical trainings. Our trainings can be on-line or physical depending on the
                      preference of the client. Examples of the trainings we conduct include working in confined spaces, hazard
                      identification and risk assessment, working-at-height, fire safety,
                     lifting safety, electrical safety, control of substances hazardous to health, Behaviour safety etc.
                </p>
            </div>
            <div class="train-sub4">
                <img src="../../static/main/images/trainings.png" />
            </div>
        </div>
        <div class="train-main1">
            <div>

                <!-- <hr /> -->
                <img src="../../static/main/images/cons.jpg" />

            </div>
            <div class="train-subn">
                <h3>SYSTEMS IMPLEMENTATION</h3>
                <h6>We Also offer consultancy for the following;</h6>
                <ul>
                    <li>HSE policy formulation</li>
                    <li>HSE documentation</li>
                    <li>HSE management system development</li>
                    <li>Risk Assesments</li>
                    <li>Health and Safety Manuals</li>
                    <li>Emergency Preapredness and Response</li>
                    <li>Hazard and Disease Surveillance</li>
                    <li>Accident Investigations</li>
                    <li>Job Hazard Analysis</li>
                </ul>
            </div>
        </div>

        {% include "main/snippets/footer.html" %}
    </section>
{% endblock %}

main/templates/main/snippets/footer.html
<div id="contactus" class="mybottom">
    <div class="mybottom1">
        <img src="../../../static/main/images/ad.jpg" alt="logo" />
        <!--<h5>Adbelt consults ltd</h5>-->
        <!--<h6>Driving Sustainability</h6>-->
    </div>
    <div class="mybottom2">
        <h5>Sitemap</h5>
        <h6>Home</h6>
        <h6>Aboutus</h6>
        <h6>Sectors</h6>
        <h6>Services</h6>
    </div>
    <!-- <div class="mybottom2">
        <h6>Contactus</h6>
        <h6>Gallery</h6>
    </div> -->
    <div class="mybottom2">
        <h5>Contactus</h5>
        <h6>P.O.Box 700868, Entebbe, Uganda</h6>
        <h6>Zzana, Entebbe Road</h6>
        <h6>Phone: +256 789 400 006  / +256 759 019 447</h6>
        <h6>Email: adbelt.adbelt@gmail.com</h6>

    </div>
</div>

main/templates/main/snippets/topbar.html
{% load static %}

<header id="main-header">
    <!-- <div class="header-now">
        <ul class="menu-now">
            <li><i class="fa fa-twitter fa-2x"    aria-hidden="true"></i></li>
            <li><i class="fa fa-facebook fa-2x" aria-hidden="true"></i></li>
            <li><i class="fa fa-instagram fa-2x" aria-hidden="true"></i></li>
            <li><i class="fa fa-youtube fa-2x" aria-hidden="true"></i></li>
            <li>Have any questions?</li> -->
            <!-- <li>info@adbelt.co.ug</li>
            <li>+256 789 400006  </li>
            <li>+256 759019447</li> -->
        <!---</ul>-->

    </div>
    <div class="header">
        <div class="navigation">
            <input type="checkbox" class="toggle-menu">
            <div class="hamburger"></div>

            <ul class="menu">
                <li>
                    <img src="../../../static/main/images/ad.jpg" alt="logo" />
                </li>
                <li><a href="{% url 'main:index' %}">HOME</a></li>
                <li><a href="{% url 'main:aboutus' %}">ABOUT US</a></li>
                <li><a  href="#sectors">SECTORS</a></li>
                <li>
                    <div class="dropdown">
                        <a href="#" class="dropbtn">SERVICES</a>
                        <div class="dropdown-content">
                            <a href="{% url 'main:training' %}">HSE CONSULTANCY</a>
                            <!-- <a href="#">HSE CONSULTING</a> -->
                            <a href="{% url 'main:eqpt' %}">SUPPLIES OF EQUIPMENT</a>
                            <a href="#inspect">INSPECTIONS</a>
                            <a href="#audit">AUDITS</a>
                            <a href="#train">TRAININGS</a>
                        </div>
                    </div>
                </li>
                <!-- <li><a href="#">TARGET CLIENTS</a></li> -->
            </ul>
            <a class="contact" href="#contactus">
                <button>CONTACT US</button>
            </a>
        </div>
    </div>
</header>
<script>
    window.addEventListener('scroll', function(){
        var header = document.getElementById('main-header');
        var scrollPosition = window.scrollY;

        //adjust this value according to when you want the effect to trigger
        var  scrollPosition = 100;
        if (scrollPosition > scrollThreshold){
            header.classList.add('dark-background');
        }else {
            header.classList.remove('dark-background');
        }
    })
</script>

main/templates/main/trainings.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
    <section id="top" class="text-center" style="overflow-x:hidden;height: 100%;">
            <!--title section-->
        {% include "main/snippets/topbar.html" %}
        <h4 class="tr-c">TRAININGS & CONSULTANCY</h4>
        <div class="nana-new">
            <div class="nana1-new">
                <img src="../../static/main/images/tr1.jpeg" alt="safe" />
            </div>
            <div class="nana1-new">
                <img src="../../static/main/images/h1.jpeg" alt="safe" />
            </div>
            <div class="nana1-new">
                <img src="../../static/main/images/he.jpeg" alt="safe" />
            </div>
            <div class="nana1-new">
                <img src="../../static/main/images/ind.jpeg" alt="safe" />
            </div>
            <!-- <div class="nana2-new">
               <h3>TRAININGS & CONSULTANCY SERVICES</h3>
            </div> -->
        </div>
        <div class="sectors-new">
            <div>
                <h4 class="sechead">OUR TRAININGS</h4>
                <h5 class="sechead5">Our trainings Include the Following.</h5>
              
                    <div class="sec-new">
                        <ol>
                            <li>Emergence Preparedness & Response</li>
                            <li>Working at Heights</li>
                            <li>Confined Space</li>
                            <li>Control of harzadous Substances</li>
                            <li>Electrical Safety</li>
                            <li>Fire Preparedness and Response</li>
                            <li>Risk | Hazard Identification and Mgt</li>
                            <li>Energy Isolation</li>
                        </ol>
                    </div>
            </div>
            <div>
                <h4 class="sechead">CONSULTANCY</h4>
                <h5 class="sechead5">Our Consultancy Services Include;</h5>
                <div class="sec-new">
                    <ol>
                        <li>Workplace inspection</li>
                        <li>Audits</li>
                        <li>Implementation of ISO 9001</li>
                        <li>Implementation of ISO 45001</li>
                        <li>Implementation of ISO 14001</li>
                        <li>Policy Formulation</li>
                        <li>HSE Manual Development</li>
                        <li>HSE Documentation</li>
                    </ol>
                </div>
            </div>
            
               
        </div>
        {% include "main/snippets/footer.html" %}
    </section>

{% endblock %}